apiVersion: v1
kind: Service
metadata:
  name: aneissh91-echo-service
  namespace: aneissh91-eks-activity
spec:
  selector:
    app: echo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
